/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ChargeHistory,
    ChargeHistoryFromJSON,
    ChargeHistoryToJSON,
    MyBilling,
    MyBillingFromJSON,
    MyBillingToJSON,
} from '../models';

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Get my billing
     */
    async billingChargeHistoryGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ChargeHistory>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/billing/charge/history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChargeHistoryFromJSON));
    }

    /**
     * Get my billing
     */
    async billingChargeHistoryGet(initOverrides?: RequestInit): Promise<Array<ChargeHistory>> {
        const response = await this.billingChargeHistoryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get my billing
     */
    async billingGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<MyBilling>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/billing`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyBillingFromJSON(jsonValue));
    }

    /**
     * Get my billing
     */
    async billingGet(initOverrides?: RequestInit): Promise<MyBilling> {
        const response = await this.billingGetRaw(initOverrides);
        return await response.value();
    }

}
