/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DownloadUsage,
    DownloadUsageFromJSON,
    DownloadUsageToJSON,
    UsageModel,
    UsageModelFromJSON,
    UsageModelToJSON,
} from '../models';

export interface UsageDownloadGetRequest {
    id?: string;
}

/**
 * 
 */
export class UsageReportApi extends runtime.BaseAPI {

    /**
     * Download Usage
     */
    async usageDownloadGetRaw(requestParameters: UsageDownloadGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DownloadUsage>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/usage/download`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DownloadUsageFromJSON(jsonValue));
    }

    /**
     * Download Usage
     */
    async usageDownloadGet(requestParameters: UsageDownloadGetRequest, initOverrides?: RequestInit): Promise<DownloadUsage> {
        const response = await this.usageDownloadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get usage report
     */
    async usageGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UsageModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/usage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageModelFromJSON));
    }

    /**
     * Get usage report
     */
    async usageGet(initOverrides?: RequestInit): Promise<Array<UsageModel>> {
        const response = await this.usageGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create Usage Report
     */
    async usagePostRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/usage`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Usage Report
     */
    async usagePost(initOverrides?: RequestInit): Promise<void> {
        await this.usagePostRaw(initOverrides);
    }

}
