/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApproveUser,
    ApproveUserFromJSON,
    ApproveUserToJSON,
    MyTeamModel,
    MyTeamModelFromJSON,
    MyTeamModelToJSON,
} from '../models';

export interface UserPendingPostRequest {
    approveUser?: ApproveUser;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Response to user pending
     */
    async userPendingGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<MyTeamModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/user/pending`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MyTeamModelFromJSON));
    }

    /**
     * Response to user pending
     */
    async userPendingGet(initOverrides?: RequestInit): Promise<Array<MyTeamModel>> {
        const response = await this.userPendingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Acc user pending
     */
    async userPendingPostRaw(requestParameters: UserPendingPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/user/pending`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApproveUserToJSON(requestParameters.approveUser),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Acc user pending
     */
    async userPendingPost(requestParameters: UserPendingPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.userPendingPostRaw(requestParameters, initOverrides);
    }

}
