/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BillingDetail,
    BillingDetailFromJSON,
    BillingDetailFromJSONTyped,
    BillingDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface BillingHistory
 */
export interface BillingHistory {
    /**
     * 
     * @type {number}
     * @memberof BillingHistory
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof BillingHistory
     */
    historyID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BillingHistory
     */
    paidStatus?: boolean;
    /**
     * 
     * @type {Array<BillingDetail>}
     * @memberof BillingHistory
     */
    detail?: Array<BillingDetail>;
    /**
     * 
     * @type {Date}
     * @memberof BillingHistory
     */
    till?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BillingHistory
     */
    from?: Date;
}

export function BillingHistoryFromJSON(json: any): BillingHistory {
    return BillingHistoryFromJSONTyped(json, false);
}

export function BillingHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'historyID': !exists(json, 'historyID') ? undefined : json['historyID'],
        'paidStatus': !exists(json, 'paid_status') ? undefined : json['paid_status'],
        'detail': !exists(json, 'detail') ? undefined : ((json['detail'] as Array<any>).map(BillingDetailFromJSON)),
        'till': !exists(json, 'till') ? undefined : (new Date(json['till'])),
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
    };
}

export function BillingHistoryToJSON(value?: BillingHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'historyID': value.historyID,
        'paid_status': value.paidStatus,
        'detail': value.detail === undefined ? undefined : ((value.detail as Array<any>).map(BillingDetailToJSON)),
        'till': value.till === undefined ? undefined : (value.till.toISOString()),
        'from': value.from === undefined ? undefined : (value.from.toISOString()),
    };
}

