/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallbackModel
 */
export interface CallbackModel {
    /**
     * 
     * @type {string}
     * @memberof CallbackModel
     */
    otpSentCallback?: string;
    /**
     * 
     * @type {string}
     * @memberof CallbackModel
     */
    otpSentErrorCallback?: string;
    /**
     * 
     * @type {string}
     * @memberof CallbackModel
     */
    otpValidatedCallback?: string;
}

export function CallbackModelFromJSON(json: any): CallbackModel {
    return CallbackModelFromJSONTyped(json, false);
}

export function CallbackModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallbackModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'otpSentCallback': !exists(json, 'otp_sent_callback') ? undefined : json['otp_sent_callback'],
        'otpSentErrorCallback': !exists(json, 'otp_sent_error_callback') ? undefined : json['otp_sent_error_callback'],
        'otpValidatedCallback': !exists(json, 'otp_validated_callback') ? undefined : json['otp_validated_callback'],
    };
}

export function CallbackModelToJSON(value?: CallbackModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'otp_sent_callback': value.otpSentCallback,
        'otp_sent_error_callback': value.otpSentErrorCallback,
        'otp_validated_callback': value.otpValidatedCallback,
    };
}

