/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadUsage
 */
export interface DownloadUsage {
    /**
     * 
     * @type {string}
     * @memberof DownloadUsage
     */
    url?: string;
}

export function DownloadUsageFromJSON(json: any): DownloadUsage {
    return DownloadUsageFromJSONTyped(json, false);
}

export function DownloadUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function DownloadUsageToJSON(value?: DownloadUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

