/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OTPMethod,
    OTPMethodFromJSON,
    OTPMethodFromJSONTyped,
    OTPMethodToJSON,
} from './';

/**
 * 
 * @export
 * @interface OTPMethods
 */
export interface OTPMethods {
    /**
     * 
     * @type {Array<OTPMethod>}
     * @memberof OTPMethods
     */
    methods?: Array<OTPMethod>;
}

export function OTPMethodsFromJSON(json: any): OTPMethods {
    return OTPMethodsFromJSONTyped(json, false);
}

export function OTPMethodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPMethods {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'methods': !exists(json, 'methods') ? undefined : ((json['methods'] as Array<any>).map(OTPMethodFromJSON)),
    };
}

export function OTPMethodsToJSON(value?: OTPMethods | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'methods': value.methods === undefined ? undefined : ((value.methods as Array<any>).map(OTPMethodToJSON)),
    };
}

