/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OTPError,
    OTPErrorFromJSON,
    OTPErrorFromJSONTyped,
    OTPErrorToJSON,
    OtpValidated,
    OtpValidatedFromJSON,
    OtpValidatedFromJSONTyped,
    OtpValidatedToJSON,
    SendStatus,
    SendStatusFromJSON,
    SendStatusFromJSONTyped,
    SendStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface OTPModel
 */
export interface OTPModel {
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    otpID?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    redirectLink?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    phoneSnippet?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    method?: string;
    /**
     * 
     * @type {Date}
     * @memberof OTPModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OTPModel
     */
    validUntil?: Date;
    /**
     * Consumer related custom data
     * @type {string}
     * @memberof OTPModel
     */
    customData?: string;
    /**
     * 
     * @type {OtpValidated}
     * @memberof OTPModel
     */
    otpValidated?: OtpValidated | null;
    /**
     * 
     * @type {SendStatus}
     * @memberof OTPModel
     */
    sendStatus?: SendStatus | null;
    /**
     * 
     * @type {OTPError}
     * @memberof OTPModel
     */
    error?: OTPError | null;
}

export function OTPModelFromJSON(json: any): OTPModel {
    return OTPModelFromJSONTyped(json, false);
}

export function OTPModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'otpID': !exists(json, 'otpID') ? undefined : json['otpID'],
        'redirectLink': !exists(json, 'redirectLink') ? undefined : json['redirectLink'],
        'phoneSnippet': !exists(json, 'phone_snippet') ? undefined : json['phone_snippet'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'validUntil': !exists(json, 'validUntil') ? undefined : (new Date(json['validUntil'])),
        'customData': !exists(json, 'custom_data') ? undefined : json['custom_data'],
        'otpValidated': !exists(json, 'otpValidated') ? undefined : OtpValidatedFromJSON(json['otpValidated']),
        'sendStatus': !exists(json, 'sendStatus') ? undefined : SendStatusFromJSON(json['sendStatus']),
        'error': !exists(json, 'error') ? undefined : OTPErrorFromJSON(json['error']),
    };
}

export function OTPModelToJSON(value?: OTPModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'otpID': value.otpID,
        'redirectLink': value.redirectLink,
        'phone_snippet': value.phoneSnippet,
        'method': value.method,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'validUntil': value.validUntil === undefined ? undefined : (value.validUntil.toISOString()),
        'custom_data': value.customData,
        'otpValidated': OtpValidatedToJSON(value.otpValidated),
        'sendStatus': SendStatusToJSON(value.sendStatus),
        'error': OTPErrorToJSON(value.error),
    };
}

