/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OTPMethod
 */
export interface OTPMethod {
    /**
     * 
     * @type {string}
     * @memberof OTPMethod
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPMethod
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OTPMethod
     */
    available?: boolean;
}

export function OTPMethodFromJSON(json: any): OTPMethod {
    return OTPMethodFromJSONTyped(json, false);
}

export function OTPMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'available': !exists(json, 'available') ? undefined : json['available'],
    };
}

export function OTPMethodToJSON(value?: OTPMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'id': value.id,
        'available': value.available,
    };
}

