/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OTPRequest
 */
export interface OTPRequest {
    /**
     * 
     * @type {string}
     * @memberof OTPRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPRequest
     */
    otpType?: string;
}

export function OTPRequestFromJSON(json: any): OTPRequest {
    return OTPRequestFromJSONTyped(json, false);
}

export function OTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'otpType': !exists(json, 'otpType') ? undefined : json['otpType'],
    };
}

export function OTPRequestToJSON(value?: OTPRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'otpType': value.otpType,
    };
}

