/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestDetail,
    RequestDetailFromJSON,
    RequestDetailFromJSONTyped,
    RequestDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface RequestTotal
 */
export interface RequestTotal {
    /**
     * 
     * @type {Array<RequestDetail>}
     * @memberof RequestTotal
     */
    detail?: Array<RequestDetail>;
    /**
     * 
     * @type {number}
     * @memberof RequestTotal
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestTotal
     */
    sent?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestTotal
     */
    validated?: number;
}

export function RequestTotalFromJSON(json: any): RequestTotal {
    return RequestTotalFromJSONTyped(json, false);
}

export function RequestTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestTotal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'detail': !exists(json, 'detail') ? undefined : ((json['detail'] as Array<any>).map(RequestDetailFromJSON)),
        'total': !exists(json, 'total') ? undefined : json['total'],
        'sent': !exists(json, 'sent') ? undefined : json['sent'],
        'validated': !exists(json, 'validated') ? undefined : json['validated'],
    };
}

export function RequestTotalToJSON(value?: RequestTotal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'detail': value.detail === undefined ? undefined : ((value.detail as Array<any>).map(RequestDetailToJSON)),
        'total': value.total,
        'sent': value.sent,
        'validated': value.validated,
    };
}

