/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestTotal,
    RequestTotalFromJSON,
    RequestTotalFromJSONTyped,
    RequestTotalToJSON,
} from './';

/**
 * 
 * @export
 * @interface RequestStat
 */
export interface RequestStat {
    /**
     * 
     * @type {RequestTotal}
     * @memberof RequestStat
     */
    lastest?: RequestTotal;
    /**
     * 
     * @type {RequestTotal}
     * @memberof RequestStat
     */
    dailyRequest?: RequestTotal;
    /**
     * 
     * @type {RequestTotal}
     * @memberof RequestStat
     */
    monthlyRequest?: RequestTotal;
    /**
     * 
     * @type {RequestTotal}
     * @memberof RequestStat
     */
    totalRequest?: RequestTotal;
    /**
     * 
     * @type {Date}
     * @memberof RequestStat
     */
    lastUpdate?: Date;
}

export function RequestStatFromJSON(json: any): RequestStat {
    return RequestStatFromJSONTyped(json, false);
}

export function RequestStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestStat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastest': !exists(json, 'lastest') ? undefined : RequestTotalFromJSON(json['lastest']),
        'dailyRequest': !exists(json, 'daily_request') ? undefined : RequestTotalFromJSON(json['daily_request']),
        'monthlyRequest': !exists(json, 'monthly_request') ? undefined : RequestTotalFromJSON(json['monthly_request']),
        'totalRequest': !exists(json, 'total_request') ? undefined : RequestTotalFromJSON(json['total_request']),
        'lastUpdate': !exists(json, 'last_update') ? undefined : (new Date(json['last_update'])),
    };
}

export function RequestStatToJSON(value?: RequestStat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastest': RequestTotalToJSON(value.lastest),
        'daily_request': RequestTotalToJSON(value.dailyRequest),
        'monthly_request': RequestTotalToJSON(value.monthlyRequest),
        'total_request': RequestTotalToJSON(value.totalRequest),
        'last_update': value.lastUpdate === undefined ? undefined : (value.lastUpdate.toISOString()),
    };
}

