/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageModel
 */
export interface UsageModel {
    /**
     * 
     * @type {string}
     * @memberof UsageModel
     */
    usageId?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageModel
     */
    usageName?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageModel
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UsageModel
     */
    csvRelativePath?: string;
    /**
     * 
     * @type {Date}
     * @memberof UsageModel
     */
    generatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsageModel
     */
    initiateAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsageModel
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsageModel
     */
    untill?: Date;
}

export function UsageModelFromJSON(json: any): UsageModel {
    return UsageModelFromJSONTyped(json, false);
}

export function UsageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usageId': !exists(json, 'usage_id') ? undefined : json['usage_id'],
        'usageName': !exists(json, 'usage_name') ? undefined : json['usage_name'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'csvRelativePath': !exists(json, 'csv_relative_path') ? undefined : json['csv_relative_path'],
        'generatedAt': !exists(json, 'generated_at') ? undefined : (new Date(json['generated_at'])),
        'initiateAt': !exists(json, 'initiate_at') ? undefined : (new Date(json['initiate_at'])),
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'untill': !exists(json, 'untill') ? undefined : (new Date(json['untill'])),
    };
}

export function UsageModelToJSON(value?: UsageModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usage_id': value.usageId,
        'usage_name': value.usageName,
        'status': value.status,
        'csv_relative_path': value.csvRelativePath,
        'generated_at': value.generatedAt === undefined ? undefined : (value.generatedAt.toISOString()),
        'initiate_at': value.initiateAt === undefined ? undefined : (value.initiateAt.toISOString()),
        'from': value.from === undefined ? undefined : (value.from.toISOString()),
        'untill': value.untill === undefined ? undefined : (value.untill.toISOString()),
    };
}

