/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OtpValidated,
    OtpValidatedFromJSON,
    OtpValidatedFromJSONTyped,
    OtpValidatedToJSON,
} from './';

/**
 * 
 * @export
 * @interface OTPModel
 */
export interface OTPModel {
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    otpID?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPModel
     */
    redirectLink?: string;
    /**
     * 
     * @type {Date}
     * @memberof OTPModel
     */
    validUntil?: Date;
    /**
     * 
     * @type {OtpValidated}
     * @memberof OTPModel
     */
    otpValidated?: OtpValidated | null;
}

export function OTPModelFromJSON(json: any): OTPModel {
    return OTPModelFromJSONTyped(json, false);
}

export function OTPModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'otpID': !exists(json, 'otpID') ? undefined : json['otpID'],
        'redirectLink': !exists(json, 'redirectLink') ? undefined : json['redirectLink'],
        'validUntil': !exists(json, 'validUntil') ? undefined : (new Date(json['validUntil'])),
        'otpValidated': !exists(json, 'otpValidated') ? undefined : OtpValidatedFromJSON(json['otpValidated']),
    };
}

export function OTPModelToJSON(value?: OTPModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'otpID': value.otpID,
        'redirectLink': value.redirectLink,
        'validUntil': value.validUntil === undefined ? undefined : (value.validUntil.toISOString()),
        'otpValidated': OtpValidatedToJSON(value.otpValidated),
    };
}

