/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OTPRequest
 */
export interface OTPRequest {
    /**
     * phone number with e164 format
     * @type {string}
     * @memberof OTPRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPRequest
     */
    otpType?: OTPRequestOtpTypeEnum;
    /**
     * Consumer related custom data in base64 format
     * @type {string}
     * @memberof OTPRequest
     */
    data?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum OTPRequestOtpTypeEnum {
    Waindirect = 'waindirect',
    Telegram = 'telegram'
}

export function OTPRequestFromJSON(json: any): OTPRequest {
    return OTPRequestFromJSONTyped(json, false);
}

export function OTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'otpType': !exists(json, 'otpType') ? undefined : json['otpType'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function OTPRequestToJSON(value?: OTPRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'otpType': value.otpType,
        'data': value.data,
    };
}

