/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVE API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OTPResponse
 */
export interface OTPResponse {
    /**
     * 
     * @type {string}
     * @memberof OTPResponse
     */
    otpID?: string;
    /**
     * 
     * @type {string}
     * @memberof OTPResponse
     */
    redirectLink?: string;
    /**
     * 
     * @type {Date}
     * @memberof OTPResponse
     */
    validUntil?: Date;
}

export function OTPResponseFromJSON(json: any): OTPResponse {
    return OTPResponseFromJSONTyped(json, false);
}

export function OTPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'otpID': !exists(json, 'otpID') ? undefined : json['otpID'],
        'redirectLink': !exists(json, 'redirectLink') ? undefined : json['redirectLink'],
        'validUntil': !exists(json, 'validUntil') ? undefined : (new Date(json['validUntil'])),
    };
}

export function OTPResponseToJSON(value?: OTPResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'otpID': value.otpID,
        'redirectLink': value.redirectLink,
        'validUntil': value.validUntil === undefined ? undefined : (value.validUntil.toISOString()),
    };
}

