/* tslint:disable */
/* eslint-disable */
/**
 * MNCOTP
 * MNCOTP API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendStatus
 */
export interface SendStatus {
    /**
     * 
     * @type {Date}
     * @memberof SendStatus
     */
    sendAt?: Date;
}

export function SendStatusFromJSON(json: any): SendStatus {
    return SendStatusFromJSONTyped(json, false);
}

export function SendStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sendAt': !exists(json, 'sendAt') ? undefined : (new Date(json['sendAt'])),
    };
}

export function SendStatusToJSON(value?: SendStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sendAt': value.sendAt === undefined ? undefined : (value.sendAt.toISOString()),
    };
}

